# The URL the site will be built for
base_url = "https://annahope.me"

title = "Anna Hope"
description = "Anna Hope's Website"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

author = "Anna Hope"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[languages.ru]
generate_feeds = true
build_search_index = true
taxonomies = [
    {name = "теги"},
]

[languages.ru.translations]
summary = "Сайт Ани Хоуп"
